version: '3.8'
networks:
  db-postgres:
    name: db-postgres
    driver: bridge
services:
  produto-service:
    image: produto-api
    build:
      dockerfile: Dockerfile
      context: .
    container_name: produto-service
    networks:
      - db-postgres
    depends_on:
      - postgres
    ports:
      - "8084:8080"
  postgres:
    image: postgres:9.4-alpine
    container_name: postgres9.4
    environment:
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    networks:
      - db-postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    restart: always
volumes:
  pgdata: { }
