version: '3.8'

networks:
  db-postgres-net:
    name: db-postgres-net
    driver: bridge

services:
  produto-service:
    image: produto-api
    build:
      dockerfile: Dockerfile
      context: .
    container_name: produto-service
    networks:
      - db-postgres-net
    depends_on:
      - postgres-service
    ports:
      - "8080:8080"
    restart: unless-stopped
  postgres-service:
    image: postgres:9.4-alpine
    container_name: postgres-service
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      - db-postgres-net
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always
volumes:
  pgdata:
    name: 'vpgdata'
