version: '3.8'

networks:
  db-postgres-net:
    name: db-postgres-net
    driver: bridge

services:
  produto-service:
    image: produto-api
    build:
      dockerfile: Dockerfile
      context: .
    networks:
      - db-postgres-net
    depends_on:
      - postgres-service
    ports:
      - "8080"
    restart: unless-stopped
  postgres-service:
    image: postgres:9.4-alpine
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    networks:
      - db-postgres-net
    volumes:
      - /usr/lib/postgres/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - postgres-service
    restart: unless-stopped